### ISSUE TITLE
STORY B7 As a third party developer I want to be able to access machine-readable metadata about the dataset

### ISSUE THREAD

**Issue by 85jesse** [beeldengeluid/opendatalab#10]
STORY B7 As a third party developer I want to be able to access machine-readable metadata about the dataset so I can find the dataset (e.g. on NDE collectieregister), find out more information and schedule updates.

- [x] Should comply to the NDE guideline for description of datasets, see: https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/#definitions

**Comment by wmelder** [comment]
find out why the current deploy doesn't provide proper datacatalogs

**Comment by phivk** [comment]
Dit lijkt me inmiddels opgelost via:
https://github.com/beeldengeluid/opendatalab/issues/181#issuecomment-974136165

Zou @85jesse dit kunnen documenteren op de APIs pagina?
https://opendatalab.vercel.app/apis

**Comment by wmelder** [comment]
zou op de data pagina moeten... niet op de apis pagina...
