### ISSUE TITLE
Task: een filter maken om alleen CC0 metadata terug te geven

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/opendatalab#12]
## stap 2: Bij deze koppeling past Willem een filter toe om “on the fly” de cc0 versie van de metadata terug te geven (hier alvast een alias met filter voor maken, bedoel je dat?)
- [ ] De DAAN data wordt gefilterd met deze [spreadsheet](https://docs.google.com/spreadsheets/d/1WnAo1r6UvslCKgpbHaAQZ6lpHL6uiTxcfWLGGI88km0/edit?usp=sharing), waarbij alleen de velden die CC0 beschikbaar zijn mogen worden gedeeld.

Note: this filtering can only be done if we control the data backend ourselves. That would have been the case when we would have had the aggregated index as backend. But the data in that index doesn't contain concept notations. Therefore it is not usable for linked data and therefore we used the storage API as backend. This is not under our control. It contains all metadata from the data flex store, so basically everything in DAAN (but filtered for some of the tenants). 

- [ ] Come up with a new solution that filters the data on openess, as described above. 
* use the beng-lod server as filter => the daan mapping needs to be filtered
* download all data from the storage API ij a file and load this in a triple store. Provide the sparql endpoint to a selected user group.
* Choose a solution for synchronisation: either load a nightly dump or use a message queue (the a-team is doing similar stuff in the thesaurus service layer).
* Proxy the sparql endpoint using a [comunica ](https://comunica.dev/) instance or using the Clariah Media Suite API.

**Comment by jblom** [comment]
@wmelder ik bedoelde dat je voor de lod server het filter "on the fly" kunt toepassen, wanneer iemand een URI opvraagt (dan geef je dus het gefilterde "cc0 compliant" record terug)

Als je dit filter zo maakt dat het makkelijk gebruikt kan worden om een ES alias (met filter query dus) kunt maken, is dit fijn, want dan kan @jwassenaarbg het gebruiken voor het daadwerkelijke aanmaken van deze alias (op de DAAN index).

**Comment by wmelder** [comment]
ja, is duidelijk... was ook geen vraag, maar ik heb hem alleen in een aparte task gestopt..

**Comment by jblom** [comment]
@wmelder beterrrrrr

**Comment by wmelder** [comment]
volgens mij is dit al gedaan. Jaap heeft de beng-lod-server configurable gemaakt met profiles.

**Comment by wmelder** [comment]
en naturrlijk zijn de eerst versie van de CC0 metdata in shcema.org formaat ook gerealiseerd.
