### ISSUE TITLE
STORY B10 As a data researcher I want to have access to the data via a SPARQL endpoint

### ISSUE THREAD

**Issue by 85jesse** [beeldengeluid/opendatalab#16]
STORY B10 As a data researcher I want to have access to the data via a SPARQL endpoint so I can perform advanced queries.

**Comment by wmelder** [comment]
uri's zijn resolvable, alleen wachten we nu nog op de lod-importer die een nieuwe dump van de linked data maakt.
die dump kan dan geladden worden in triples store, waarmee ook daadwerkelijk alle URI's in de triples store zijn geupdate

**Comment by wmelder** [comment]
dump lod-importer is klaar, nu nog laden in AWS (actie martijn)
de sparql UI is al wel beschikbaar op https://cat.apis.beeldengeluid.nl/sparql Dit is tevens de URL voor het (machine readable) sparql endpoint. Allen voor humans wordt er doorgestuurd naar de UI. Dit moet nog iets netter worden ingericht in de proxy server, zodat er a) geen URL met vercel er in te zien is, b) er op basis van accept header wordt doorgestuurd naar de juiste plek en niet eerst een doorverwijzing naar cliopatria (voor humans).

**Comment by wmelder** [comment]
de data is geladen zie https://github.com/beeldengeluid/opendatalab/issues/255
het goed inrichten van de proxy is nog ongoing... maar de sparql UI is beschikbaar..
