### ISSUE TITLE
rol een VM met een cliopatria triple store uit in AWS

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/opendatalab#180]
* run docker image
Het script van vorig jaar is nog beschikbaar: https://github.com/beeldengeluid/x-omgeving/blob/master/ansible/cliopatria.yml
* load n-triples
Inmiddels weten we dat de schema.org dump geen informatie bevat die we niet als open data mogen publiceren.
De data kan dus gewoon als één grote dump in de triple store geladen worden.

**Comment by wmelder** [comment]
#16

**Comment by MartijnBNG** [comment]
Het script van vorig jaar is nog beschikbaar: https://github.com/beeldengeluid/x-omgeving/blob/master/ansible/cliopatria.yml

Zoals genoemd in de planning was toen ook het belangrijkste vraagstuk de data.

**Comment by wmelder** [comment]
Inmiddels weten we dat de schema.org dump geen informatie bevat die we niet als open data mogen publiceren.
De data kan dus gewoon als één grote dump in de triple store geladen worden.

Verder vermoed ik dat we de dockercliopatria source regelmatig moeten updaten en de image builden. er komen nog regelmatig updates en die wil je ook verwerken. Dit en het regelmatig updaten van de data moeten we ook regelen.

**Comment by wmelder** [comment]
File locaties op Zorin:
* Data file (cat data in ntriples format):
```/data/graphs/nisv/aggr/nisv_cat_daan_sdo_20210827.nt```
* Prolog script for loading the data file on startup:
```/data/graphs/nisv/aggr/load_daan.pl```
* Docker-compose configuration file:
```/home/wmelder/docker/cliopatria_daan/docker-compose.yml```

Although I build the ClioPatria docker image from the [source repository](https://github.com/jrvosse/ClioPatriaDocker), I think it is possible to just use the[ latest image from the Docker hub](https://hub.docker.com/r/jrvosse/cliopatria) as well.

**Comment by wmelder** [comment]
http://54.155.137.226/

**Comment by MartijnBNG** [comment]
Nieuwe (definitieve) url:
http://54.217.179.144/

**Comment by wmelder** [comment]
The endpoint at http://54.217.179.144/sparql can be used and responds as expected. I tested this using a local instance of the yasgui example UI.
This issue is done

**Comment by wmelder** [comment]
Dit werkt niet met de AWS deploy:
* ClioPatria AWS sparql endpoint moet queryable zijn voor Comunica client.

Hoe te testen:

**Comment by wmelder** [comment]
Martijn heeft het geregeld: https://cat.apis.beeldengeluid.nl/sparql
Willem Melder: met als bijeffect dat de redirect naar yasgui niet meer kan... :thumbsup: dus wel sparql endpoint, maar ook alleen dat...
