### ISSUE TITLE
fetch Open Data Sources from BenG LOD server

### ISSUE THREAD

**Issue by phivk** [beeldengeluid/opendatalab#181]
- [ ] ~Philo to check in with @wmelder re BenG LOD API spec~
- [ ] ~fetch list of available datasets~
- [ ] ~for each dataset, fetch metadata~

To consider: fetch datacatalog with datasets via Linked Data native way via SPARQL or GraphQL-LD

**Comment by wmelder** [comment]
https://github.com/beeldengeluid/beng-lod-server/wiki/Open-Data-Catalog

**Comment by phivk** [comment]
@wmelder zou je alvast een JSON-LD geformateerde file kunnen delen van de beschikbare datasets, zoals die op dit moment wordt teruggegeven door de API?

**Comment by wmelder** [comment]
deze is er wel: http://data.rdlabs.beeldengeluid.nl/id/dataset/0001
er zitten momenteel 14 datasets in..

**Comment by jblom** [comment]
@MartijnBNG @wmelder and all endpoints are active, which is not correct, since only the dataset endpoints are allowed? The ansible config `settings-odl.py` seems fine though... 

Will check this later when I have some time today

**Comment by wmelder** [comment]
@phivk het beschikbaar zijn van de datasets is gefixt.

**Comment by phivk** [comment]
vandaag hebben @wmelder en ik besproken dat het meer future proof is om datasets als native Linked Data (via SPARQL of GraphQL-LD) op te vragen, ipv de huidige JSON geserialiseerde representatie...

**Comment by wmelder** [comment]
ter aanvulling: ``` JSON geserialiseerde representatie``` is JSON-LD.

**Comment by wmelder** [comment]
- [x] dump versturen aan Philo
- [ ] als de lod importer klaar is regelen op de beng-lod server

**Comment by wmelder** [comment]
lod-importer download duurt helaas erg lang >14 dagen... issue aanmaken om te verbeteren...
momenteel ~ 450k items per dag (van de ~ 8M)

**Comment by wmelder** [comment]
ok er kunnen nog dingetjes aan de data veranderen, maar je kunt de data dus ophalen van de beng-lod-server
