### ISSUE TITLE
task: design a pattern for periodically updating software and data for sparql endpoint

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/opendatalab#185]
Dit is een vervolg issue op #180 

* think about periodical refreshments (and I don't mean drinks)
we zullen de dockercliopatria source regelmatig moeten updaten en de image builden. er komen nog regelmatig updates en die wil je ook verwerken. Dit en het regelmatig updaten van de data moeten we ook regelen. 

Here is the x-omgeving periodical update [wiki](https://github.com/beeldengeluid/x-omgeving/wiki/DEVOPS:-Periodically-import-and-update-data)

**Comment by jblom** [comment]
@wmelder goed om dit idd binnenkort met @MartijnBNG  op te pakken

**Comment by MartijnBNG** [comment]
Inderdaad! Schiet maar wat in, mijn agenda is up-to-date :)
