### ISSUE TITLE
Task: (stap 1) Interlink the beng LOD server to the ES aggregated index

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/opendatalab#2]
## stap 1: Willem koppelt beng LOD server aan index van Johannes (de huidige “importer index” => daan-aggregated-prod-2020)

- [x] Maken van een architectuur plaatje. en linken aan [roadmap](https://docs.google.com/document/d/1P34ij2CGjwIIFJ9HHuyah9OPkmlThbN7x5xEYgGA9Vk/edit#heading=h.m5uo1qvce1e3).
en in [Github roadmap](https://github.com/beeldengeluid/opendatalab#workspaces/main-board-5bd99e4e4b5806bc2befbe27/roadmap?repos=189964774,66377114,87549061,155552812,67128754,155689321,66378006,111376066,105859644,155345526,77676496,193917291,222418901,215052642,247954627,74037147,294071746,317512450)

- [x] Gebruik het schema zoals eerder =>[ infrastructure step](https://docs.google.com/document/d/1P34ij2CGjwIIFJ9HHuyah9OPkmlThbN7x5xEYgGA9Vk/edit#heading=h.1hhxeeb6iwx3)

- [ ] The internal schema needs to be published or needs to be mapped to standardized external format. (#14)

- [ ] The dataset is published in a standardised format (Schema.org) (#3)
Note: This seems to be a more important requirement than before. The (internal) NISV schema is ideal for mapping all of our data. But for disseminating data is preferable to map the data to the (external) widely in use schema.org

- [x] Op basis van de [huidige beng-lod-server](http://data.rdlabs.beeldengeluid.nl/) maken van een route die de DAAN items resolved als linked data. 
Onderzoeksvraag: Hoe zien de URI's er uit? Welk (sub-)domein komt uiteindelijk beschikbaar? (data.rdlabs.beeldengeluid.nl voor ontwikkeling)

Zie deze [story](https://github.com/beeldengeluid/beng-lod-server/issues/16)
- [x] de applicatie voorzien van unittests
- [x] De requests maken gebruik van de huidige import index van johannes: daan-aggregated-prod-2020 op de server: deves2001
Note: This can not be done, because the datga doesn't contain Concept URI's. An alternative is used (storage API).
- [x] Alternatief onderzoeken: niet geaggregeerde index: http://dev-es-bng-01.beeldengeluid.nl/head
NOTE: denk eraan bij de flexstore dat je moet filteren op GPP 
Onderzoeksvraag: welke index biedt de beste mogelijkheden om niet geaggregeerde resources op te vragen?
NOTE: the alternative mentioned above is referred to as the flex data store. There is also an accetance version. It is not meant to be used (for a reason unknown). Therefore we are now using the [storage API](https://docs.google.com/document/d/120WKMft09IXKB25XejnpV8QZHJmDZyWYfVIDnTe8-Rs/edit?usp=sharing). This gives access to the same data, but it is mediated by an API. 

- [x] De data wordt in een Graph geladen en uitgeserveerd in het gewenste formaat (via content negotiation).
- [ ] betere weergave via swagger UI van de content type in the request headers

**Comment by wmelder** [comment]
https://github.com/beeldengeluid/beng-lod-server/issues/16

**Comment by wmelder** [comment]
Voor wat betreft HTML weergave: https://github.com/beeldengeluid/opendatalab/issues/4

**Comment by mwigham** [comment]
See [this document](https://docs.google.com/document/d/1tdI7AEaC5T3LFXABrTdyQOI4pGgqTbIhrECHdu1oXuU/edit#heading=h.nmsnt6ckvscq) for an overview of IDs in DAAN. OAI-PMH requests use the DAAN id, which is DAAN specific. The site ID is intended for broader use than DAAN alone, and as such may be a better basis for our URIs.

**Comment by wmelder** [comment]
- eerste stapjes gezet, maar komende sprint grote stap zetten

**Comment by wmelder** [comment]
@mari  You wrote: "The site ID is intended for broader use than DAAN alone, and as such may be a better basis for our URIs."

Currently, we are using the document _id in combination with the level (program, series, etc.) as basis for the URI. Is it also available for series, seasons, etc.?

**Comment by mwigham** [comment]
In the aggregated index each level has an id: program.id (same as _id), series.id, season.id etc. Or did you mean the site_id? This is also available at all levels: series.site_id, program.site_id etc..

**Comment by wmelder** [comment]
This issue is quite large, almost an Epic, so I will create a new task for the schema.org mapping part.

**Comment by wmelder** [comment]
Closing this issue. Please go fluttering to the [EPIC that rules them all](https://github.com/beeldengeluid/opendatalab/issues/1)...
