### ISSUE TITLE
Link from labs to projects

### ISSUE THREAD

**Issue by roelandordelman** [beeldengeluid/opendatalab#214]
@phivk  Is it possible to link from within the labs pages to the projects (that are attached to a lab but are described on another page)?

**Comment by phivk** [comment]
yes, for every Project, you can specify which Lab it belongs to:
![3745982A-E26B-4292-914F-3E807698D0AC-1154-0000BF4D63263235](https://user-images.githubusercontent.com/902958/139913359-e9872b52-fe70-4a44-85a7-e9a97adddf32.png)

they should then show up on the respective Lab page, see e.e. MediaScape Project on the [OpenDataLab page](https://opendatalab-beeldengeluid.vercel.app/labs/opendatalab):
![76D1FFAC-3578-43A5-96E8-40B153E8D673-1154-0000BF6BD2FAB2CD](https://user-images.githubusercontent.com/902958/139913693-cebffb85-dd7a-4ee1-8d81-ab1089f915ad.png)

Looks like you've already selected a Lab for projects, e.g. I would expect VisXP to show up under CLARIAH Media Suite. Not sure why it isn't. I will investigate.
