### ISSUE TITLE
Can we add a field to the project pages for a link to project website

### ISSUE THREAD

**Issue by roelandordelman** [beeldengeluid/opendatalab#215]
@phivk Can we add a field to the project pages for a link to project website

**Comment by phivk** [comment]
yes that's possible!

**Comment by phivk** [comment]
fixed via https://github.com/beeldengeluid/opendatalab/commit/eeede03945a8673cb00281d5b48bd710111285c1 and https://github.com/beeldengeluid/opendatalab/commit/292ad90b84b87e9aac976684acba3e4ddcb05383
