### ISSUE TITLE
task: load the latest dump file into the AWS cliopatria 

### ISSUE THREAD

**Issue by wmelder** [beeldengeluid/opendatalab#255]
* location of the latest dump (n-triples) that needs to be loaded 
```/data/graphs/nisv/aggr/nisv_cat_daan_sdo_20211119.nt``` (on Zorin)

* make sure the prolog script points to the right file:
```ansible\files\cliopatria_daan\load_daan.pl``` (in x-omgeving repo)

This part contains the file name:
```
% Load n-triples file with all the RDF data from the DAAN catalogue (CC0 only).
load_daan :-
    rdf_load('**data/nisv/nisv_cat_daan_sdo_20210827.nt**',
            [register_namespaces(true),
            graph('http://data.rdlabs.beeldengeluid.nl/cat_daan_sdo/')]).
```

* make sure the data that was loaded before is dropped (contact Wmelder about this)

* make sure the store is published using the same URL (otherwise the proxy points to the wrong server)
```http://54.217.179.144/```

* make sure the server is not accessible for the world (only expose the /sparql endpoint, via https://cat.apis.beeldengeluid.nl/sparql that is configured in the http proxy).

NB please schedule task right away, since we already waited so long for the lod-importer. Muchos gracias.

**Comment by MartijnBNG** [comment]
Reloaded it, appears to have worked? Site is not yet available though. Must check again tomorrow

**Comment by wmelder** [comment]
ja. hij parset eerst de hele handel en stopt deze in een database. dan start hij de server opnieuw op in daemon mode en laadt de database. 
hoop ik :pray:

**Comment by wmelder** [comment]
aantallen komen overeen met die uit de dump file: 

sdo:CreativeWork 2046446
sdo:CreativeWorkSeason 11880
sdo:CreativeWorkSeries 68128
sdo:Clip 5614295

consider it done!
