### ISSUE TITLE
display name props for dataset fields

### ISSUE THREAD

**Issue by phivk** [beeldengeluid/opendatalab#265]
- [x] Creator
- [x] Publisher
- [x] DataCatalog
- [x] License (for CC0)

**Comment by phivk** [comment]
thanks for clearing that up, I missed the fact that DataCatalog has a name too!

**Comment by wmelder** [comment]
great! and I agree that you need to add an href to the name too, as you mentioned in the sprint demo.

**Comment by phivk** [comment]
<img width="542" alt="A81ABEC0-D8EB-4F27-BB70-D6DAE2AB75FA-501-0001E3D1FEDC663A" src="https://user-images.githubusercontent.com/902958/150147979-66f0108b-9940-47b6-a633-b46bbe3152d0.png">
