### ISSUE TITLE
Upgrade to Nuxt 3

### ISSUE THREAD

**Issue by gb-beng** [beeldengeluid/opendatalab#456]
> On December 31st, 2023, Vue 2 will reach End of Life (EOL), and with it Nuxt 2. Both Vue and Nuxt will continue being available and working for many people, but at the same time, many companies and users will want to transition to Nuxt 3 (and we'd encourage this!).

Also consider Nuxt Bridge

> In addition, there is Nuxt Bridge. It was built as a module to bring features and bug fixes from Nuxt 3 back to Nuxt 2, although it has not yet been released in a stable version. We plan to stabilise and release it in the next month or so, but our main focus over the course of the year will be on helping people transition to Nuxt 3.

https://nuxt.com/vision-2023#migrating-to-nuxt-3

Would also resolve some of the security warnings we cannot resolve:

https://github.com/beeldengeluid/x-omgeving/issues/709

**Comment by phivk** [comment]
as part of this migration we should move to Node version 18:
https://github.com/beeldengeluid/labs.beeldengeluid.nl/issues/444

**Comment by phivk** [comment]
keeping track of my research and migration steps here:

- skim through https://nuxt.com/docs/migration/configuration
- read through https://v3-migration.vuejs.org/breaking-changes/; looks like most breaking changes don't affect our code much.
- web searched for "how to migrate nuxt 2 to nuxt 3", most promising results include:
  - https://debbie.codes/blog/migrating-nuxt2-nuxt3/ (Debbie is an active Nuxt ambassador); suggests starting new nuxt3 project for easiest migration.
  - https://harlanzw.com/blog/nuxt-3-migration-cheatsheet; suggests a couple of [pre-migration steps](https://harlanzw.com/blog/nuxt-3-migration-cheatsheet#pre-migration) which seem a useful addition to Debbie's guide above.

**Comment by phivk** [comment]
Philo & Govert Calling about plan of action status:
- outstanding:
  - Vuetify update errors and warning: `npm run lintfix` throws: `(37 problems (36 errors, 1 warning))`
  - ensure styling/theme config is loaded and used in navbar colors etc
  - `VisualMain` component to be properly connected with PanZoom dependency
  - introduce other pages, besides index and about.
