### ISSUE TITLE
STORY B2 As a third party developer I want to be able to have access to the data in machine readable format(s)

### ISSUE THREAD

**Issue by 85jesse** [beeldengeluid/opendatalab#5]
STORY B2 As a third party developer I want to be able to have access to the data in machine readable format(s) so I can have my application process the data.

- [x] the formats need to be widely acccepted (e.g. JSON-LD)

**Comment by wmelder** [comment]
this is done... you can query for data here: https://cat.apis.beeldengeluid.nl/sparql 
Will notify NOB about it...

**Comment by wmelder** [comment]
also, the data is available per item on its URI in the data domain using the beng-lod-server.
http://data.beeldengeluid.nl/id/{cat_type}/{daan_id}
OpenAPI UI available here: http://data.beeldengeluid.nl/
