### ISSUE TITLE
Create new main feature branch

### ISSUE THREAD

**Issue by gb-beng** [beeldengeluid/opendatalab#512]
Replace iframe visualisation on the Data Dashboard tab for MOZ with 'native' visualizations based on output of search API aggregations.

**Comment by Veldhoen** [comment]
- [ ] Merge new main in feature branch
- [ ] Manually create vegalite specification for at least one visualization
- [ ] Get visualization to display proper
- [ ] Put visualizations in the right place
- [ ] Auto-generate vegalite specifications based on generated data 
- [ ] Integrate improvements from #515

**Comment by Veldhoen** [comment]
NB: Vega-Altair - Vegalite for Python. Integrate in Notebook so that it can use the same visualization specs?
