### ISSUE TITLE
Last update value incorrect

### ISSUE THREAD

**Issue by gb-beng** [beeldengeluid/opendatalab#526]
This seems to be pulled from metadata in the git repo, via nuxt-content:

https://github.com/beeldengeluid/labs.beeldengeluid.nl/blob/c47f797ff472e604634a10dab91179c8dc4b48b4/components/ArticlePage.vue#L49-L51

... but it is buggy, all dates seem equal deploy date. see e.g. https://labs.beeldengeluid.nl/archive/waisda.

Also see https://github.com/nuxt/content/issues/913.

**Comment by KleinRana** [comment]
For now we decided to delete the date.
