### ISSUE TITLE
Bug: TypeError: vue.openBlock is not a function during Vercel deploy

### ISSUE THREAD

**Issue by phivk** [beeldengeluid/opendatalab#82]
To investigate locally. Vercel log below ([src](https://vercel.com/beeldengeluid/opendatalab/6jYpDQu1DVmHc7iUs2T9o7EfyAhX)):

17:46:19.933 | [error]  /nl
-- | --
17:46:19.933 | TypeError: vue.openBlock is not a function
17:46:19.933 | at a.render (/vercel/workpath0/node_modules/vue-panzoom/dist/vue-panzoom.umd.js:112:19)
17:46:19.933 | at a.t._render (/vercel/workpath0/node_modules/vue/dist/vue.runtime.common.prod.js:6:35273)
17:46:19.933 | at /vercel/workpath0/node_modules/vue-server-renderer/build.prod.js:1:70637
17:46:19.933 | at Yi (/vercel/workpath0/node_modules/vue-server-renderer/build.prod.js:1:67201)
17:46:19.933 | at io (/vercel/workpath0/node_modules/vue-server-renderer/build.prod.js:1:70613)
17:46:19.933 | at ro (/vercel/workpath0/node_modules/vue-server-renderer/build.prod.js:1:70244)
17:46:19.933 | at _t.eo [as renderNode] (/vercel/workpath0/node_modules/vue-server-renderer/build.prod.js:1:67491)
17:46:19.933 | at _t.next (/vercel/workpath0/node_modules/vue-server-renderer/build.prod.js:1:20507)
17:46:19.933 | at n (/vercel/workpath0/node_modules/vue-server-renderer/build.prod.js:1:18719)
17:46:19.934 | at /vercel/workpath0/node_modules/vue-server-renderer/build.prod.js:1:68602
17:46:19.934 | at eo (/vercel/workpath0/node_modules/vue-server-renderer/build.prod.js:1:68610)
17:46:19.934 | at /vercel/workpath0/node_modules/vue-server-renderer/build.prod.js:1:70711
17:46:19.934 | at Yi (/vercel/workpath0/node_modules/vue-server-renderer/build.prod.js:1:67201)
17:46:19.934 | at io (/vercel/workpath0/node_modules/vue-server-renderer/build.prod.js:1:70613)
17:46:19.934 | at ro (/vercel/workpath0/node_modules/vue-server-renderer/build.prod.js:1:70244)
17:46:19.934 | at _t.eo [as renderNode] (/vercel/workpath0/node_modules/vue-server-renderer/build.prod.js:1:67491)

**Comment by whelmich** [comment]
Fixed by https://github.com/beeldengeluid/opendatalab/commit/0c7d856bf438b2655855ecd58af42e71c1c153db
