### ISSUE TITLE
STORY B6 As a third party developer I want to be able to use an endpoint to run queries on the data

### ISSUE THREAD

**Issue by 85jesse** [beeldengeluid/opendatalab#9]
STORY B6 As a third party developer I want to be able to use an API to run queries on the data so I can use the output of those queries in my application.

- [x] The API should be conform existing API standards

**Comment by wmelder** [comment]
Feedback on example UI and possible interesting example user queries: 
https://docs.google.com/document/d/1UQFQe45d97xr6aP5h6WDSP2wfq4oPIl7bOHAnvViBic/edit?usp=sharing

**Comment by wmelder** [comment]
- [x] The API should be conform existing API standards

I checked off this task, because a SPARQL endpoint is provided. But maybe, something like the suggestions [here ](https://code.google.com/archive/p/linked-data-api/) is needed

**Comment by jblom** [comment]
Jaap arranges the apis domain

**Comment by wmelder** [comment]
het is geregeld... https://cat.apis.beeldengeluid.nl/sparql

moeten alleen de redirection voor de UI netjes inrichten...

kan verder gesloten worden
